With the update to fast-xml-parser you can no longer just use xml.parse. You now have to create an instance of the XMLParser object from that library.
This fixes that and now allows the sitemap functionality to work again.

Broken example:

```
npx evaluatory --sitemap https://www.foo.com/sitemap.xml -m axe-core,html-validate -o foo-report
Need to install the following packages:
  evaluatory
Ok to proceed? (y)
× xml.parse is not a function
i Adding 0 URLs from the sitemap.
× Error: Specify URLs to evaluate.
    at main (C:\Users\foo\AppData\Local\npm-cache\_npx\40cdadd758bd873b\node_modules\evaluatory\bin\evaluatory.js:39:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```